title: Marcela Galvis Restrepo  # your name (or website title) here
logo: "/images/IMG_20211203_113415 (1).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
Welcome to my personal website, I am a machine learning researcher and analytics professional.
  
 Well rounded analytics professional with 10+ years of experience using data to aid decision making in a variety of sectors, from the international development sector, to education, science, technology and innnovation. 
 Currently, finishing my PhD thesis where I design algorithms to improve the fairness and interpretability of machine learning models in the presence of high-cardinality categorical predictors using tools from mathematical optimization and data science. 
 I am interested in applying these new methods to aid decision making in knowledge intensive industries.
  <br><br>
  
  <a href="https://www.linkedin.com/in/marcelagalvis/">View My LinkedIn Profile</a>

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
