title: Marcela Galvis Restrepo  # your name (or website title) here
logo: "/images/IMG_20211203_113415 (1).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Welcome to my personal website, I am a machine learning researcher and analytics professional
  <br><br>
  
  <a href="https://www.linkedin.com/in/marcelagalvis/">View My LinkedIn Profile</a>

  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
